Refactoring class of model and frontend
andreldsa/treinamento_eciis pull request #5
Opened 2017-05-08 18:19 UTC by Luiz-FS

Client almost ready, only remains to implement the login.

2017-05-08 18:28 UTC, andreldsa commented on luiz/to-do-list/app/js/app.js
>          $mdThemingProvider.theme('dark-grey').backgroundPalette('grey').dark();
Create function to setup material variables.

2017-05-08 18:29 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
remover linha em branco = RLB

2017-05-08 18:30 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
RLB

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
RLB

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
RLB

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +                console.log(response.status);
Remove all console.log's

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
rlb

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/tarefasController.js
> +        }
add ;

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/tarefasController.js
> +        }
Check all finished lines with ;

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/app/js/service/todoService.js
> +            return $http.get('http://' + location.host + '/api/todo')
Extract URI to constant.

eg.: var TODO_URI = '/api/todo'

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/main.py
remove all blank lines

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/main.py
> +        self.response.write(id)
always return json format

2017-05-08 18:39 UTC, andreldsa commented on luiz/to-do-list/model/controller.py
> +class OperacoesTarefas(object):
Move inside Tarefa Model

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
>                  console.log(response.data);
remover console.log

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +                window.location.replace(response.data.login_url);
porque está redirecionando para login?

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/tarefasController.js
>                  delete vm.tarefa
cuidado! Isso pode ser fonte de bugs, ao salvar a tarefa o melhor seria sair da página ou limpar o model vm.tarefa, você fazendo um delete o model irá ficar undefined e pode gerar erros.

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/tarefasController.js
>              }, function(response){})
;

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/tarefasController.js
>                  delete vm.tarefa
inserir ;

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/service/todoService.js
> +            return $http.get('/api/todo')
extrar uri para constante

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/service/todoService.js
>          }
inserir ;

2017-05-09 11:34 UTC, andreldsa commented on luiz/to-do-list/app/js/service/todoService.js
>          }
inserir ;

2017-05-09 14:45 UTC, Luiz-FS commented on luiz/to-do-list/app/js/service/todoService.js
>          }
Coloquei

2017-05-09 14:45 UTC, Luiz-FS commented on luiz/to-do-list/app/js/service/todoService.js
>          }
Coloquei

2017-05-09 14:46 UTC, Luiz-FS commented on luiz/to-do-list/app/js/service/todoService.js
> +            return $http.get('/api/todo')
Extraí

2017-05-09 14:46 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/tarefasController.js
>              }, function(response){})
Coloquei

2017-05-09 14:47 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/tarefasController.js
>                  delete vm.tarefa
Consertei o problema e coloquei o ;

2017-05-09 14:56 UTC, andreldsa commented on luiz/to-do-list/app/index.html
> +<body ng-app="panelGroupsDemo">
Voltar ao nome original do app e sempre usar ng-cloak no body

2017-05-09 14:56 UTC, andreldsa commented on luiz/to-do-list/app/index.html
>    <script src="/js/service/todoService.js"></script>
corrigir ou remover

2017-05-09 14:56 UTC, andreldsa commented on luiz/to-do-list/app/js/controllers/tarefasController.js
>              }, function(response){})
mais um ;

2017-05-09 14:56 UTC, andreldsa commented on luiz/to-do-list/app/js/service/todoService.js
>          }
;

2017-05-09 14:56 UTC, andreldsa commented on luiz/to-do-list/app/js/service/todoService.js
>          }
;

2017-05-09 14:56 UTC, andreldsa commented on luiz/to-do-list/app/js/service/todoService.js
>  })()
;

2017-05-09 14:56 UTC, andreldsa commented on luiz/to-do-list/util/util.py
> +      #self.redirect(logout_url)
corrigir ou remover

2017-05-09 17:18 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
Removido

2017-05-09 17:18 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
Removido

2017-05-09 17:18 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
Removido

2017-05-09 17:19 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +
Removido

2017-05-09 17:22 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/tarefasController.js
> +        }
Feito

2017-05-09 17:22 UTC, Luiz-FS commented on luiz/to-do-list/app/js/service/todoService.js
> +            return $http.get('http://' + location.host + '/api/todo')
Feito

2017-05-09 17:23 UTC, Luiz-FS commented on luiz/to-do-list/main.py
Feito

2017-05-09 17:23 UTC, Luiz-FS commented on luiz/to-do-list/main.py
> +        self.response.write(id)
Modificado

2017-05-09 17:23 UTC, Luiz-FS commented on luiz/to-do-list/model/controller.py
> +class OperacoesTarefas(object):
Movido

2017-05-09 17:25 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
>                  console.log(response.data);
Removido

2017-05-09 17:27 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +                window.location.replace(response.data.login_url);
Caso o usuário não esteja logado será retornado a url da página de login, por isso o redirecionamento, a priore essa foi a única solução que encontrei, já que o self.redirect do app engine não está redirecionando de fato.

2017-05-10 16:42 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/listaTarefasCtrl.js
> +                console.log(response.status);
Removido

2017-05-10 16:43 UTC, Luiz-FS commented on luiz/to-do-list/util/util.py
> +      #self.redirect(logout_url)
Método corrigido

2017-05-10 16:43 UTC, Luiz-FS commented on luiz/to-do-list/app/js/service/todoService.js
>  })()
Feito

2017-05-10 16:44 UTC, Luiz-FS commented on luiz/to-do-list/app/js/service/todoService.js
>          }
Feito

2017-05-10 16:44 UTC, Luiz-FS commented on luiz/to-do-list/app/js/controllers/tarefasController.js
>              }, function(response){})
Feito

2017-05-10 16:44 UTC, Luiz-FS commented on luiz/to-do-list/app/js/service/todoService.js
>          }
Feito

2017-05-10 16:45 UTC, Luiz-FS commented on luiz/to-do-list/app/index.html
>    <script src="/js/service/todoService.js"></script>
Corrigido

2017-05-10 16:45 UTC, Luiz-FS commented on luiz/to-do-list/app/index.html
> +<body ng-app="panelGroupsDemo">
Problema resolvido

2017-05-11 13:56 UTC, andreldsa commented on luiz/to-do-list/util/util.py
>        self.response.headers['Content-Type'] = 'application/json; charset=utf-8'
rever lógica de acoplamento do util.

2017-05-11 14:09 UTC, andreldsa reviewed
Do it!

2017-05-12 12:13 UTC, andreldsa commented on luiz/to-do-list/app/js/app.js
>          $mdIconProvider
pode remover, não está sendo usado.

2017-05-12 12:13 UTC, andreldsa commented on luiz/to-do-list/main.py
> +            print exception.message
remover

2017-05-15 13:32 UTC, mayzabeel commented on luiz/to-do-list/app.yaml
> +- url: /login
aqui tu pode colocar login/logout juntos como Dalton fez
- url: /(login|logout)
  script: main.app

2017-05-15 13:32 UTC, mayzabeel commented on luiz/to-do-list/app/js/controllers/appCtrl.js
> +        vm.teste = true;
remover

2017-05-15 13:32 UTC, mayzabeel commented on luiz/to-do-list/app/js/controllers/tarefasController.js
> +
rlb

2017-05-15 13:32 UTC, mayzabeel commented on luiz/to-do-list/app/js/controllers/tarefasController.js
> +    app.controller('tarefasController', function($http, taskService) {
Não é necessário ter dois controllers para tratar as tarefas. Tenta colocar tudo em um só, litaTarefasCtrl e tarefasController. Fica confuso ter dois para tratar de tarefas.

2017-05-15 17:59 UTC, mayzabeel approved these changes

2017-05-16 11:29 UTC, andreldsa requested changes
Fix! Muito bom, melhorou bastante a arquitetura do sistema.

2017-05-16 11:29 UTC, andreldsa commented on luiz/to-do-list/app/js/service/taskService.js
> +            window.alert('Faça login para poder realizar esta operação!');
lógica de controller

2017-05-16 11:29 UTC, andreldsa commented on luiz/to-do-list/app/js/service/taskService.js
> +        var _enableProgress = false;
lógica de controller

2017-05-16 11:29 UTC, andreldsa commented on luiz/to-do-list/model/models.py
> +def gravatar_url(email):
mover pro utils

2017-05-16 11:29 UTC, andreldsa commented on luiz/to-do-list/model/models.py
> +    return "http://www.gravatar.com/avatar/%s.jpg" % hash_md5.hexdigest()
usando a url: "http://www.gravatar.com/hash_email.json" pega o profile com várias informações

2017-05-16 18:31 UTC, andreldsa requested changes

2017-05-16 18:31 UTC, andreldsa commented on luiz/to-do-list/main.py
> +    @util.login_required
dá pra importar o login_required diretamente do util

2017-05-16 18:31 UTC, andreldsa commented on luiz/to-do-list/main.py
>          user_data = {
move isso para um método dentro do modelo User

2017-05-16 18:31 UTC, andreldsa commented on luiz/to-do-list/main.py
>          self.response.headers['Content-Type'] = 'application/json; charset=utf-8'
dá pra fazer um decorator com esse header, assim podemos decorar os métodos que retornam json.

2017-05-16 18:54 UTC, ruanres commented on luiz/to-do-list/model/models.py
> +        user = ndb.Key('User','luiz.silva@ccc.ufcg.edu.br').get()
Isso pode ser feito de forma mais simples utilizando o método get_by_id

2017-05-16 19:46 UTC, ruanres approved these changes

2017-05-16 20:06 UTC, andreldsa approved these changes
Massa.

2017-05-16 20:10 UTC, merged